services:
  app:
    build:
      dockerfile: "./Dockerfile"
      context: "./"
    ports:
      - "5050:8000"
  pg:
    image: postgres
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"