"""create a table for reviews with files-right

Revision ID: 84f98af6b1d8
Revises: 45dfd4a5c14b
Create Date: 2025-10-29 15:37:49.744832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84f98af6b1d8"
down_revision: Union[str, Sequence[str], None] = "45dfd4a5c14b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviewfiles",
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("fk_reviewfiles_review_id_reviews"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviewfiles")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviewfiles")
    # ### end Alembic commands ###
