"""remove_price_from_basket_products

Revision ID: 80bccd4ceb30
Revises: 5b4d7acc85c9
Create Date: 2025-10-18 01:07:33.117775

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80bccd4ceb30"
down_revision: Union[str, Sequence[str], None] = "5b4d7acc85c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("basket_products", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "basket_products",
        sa.Column(
            "price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
