"""users_table_add_login

Revision ID: e50d932a150c
Revises: a59629a2094f
Create Date: 2025-09-29 00:12:25.668172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e50d932a150c"
down_revision: Union[str, Sequence[str], None] = "a59629a2094f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("login", sa.String(), nullable=False))
    op.create_unique_constraint(op.f("uq_users_login"), "users", ["login"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_login"), "users", type_="unique")
    op.drop_column("users", "login")
    # ### end Alembic commands ###
