"""update table name

Revision ID: 4e965b423a4d
Revises: 84f98af6b1d8
Create Date: 2025-10-29 15:38:41.167166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e965b423a4d"
down_revision: Union[str, Sequence[str], None] = "84f98af6b1d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_files",
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("fk_review_files_review_id_reviews"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_files")),
    )
    op.drop_table("reviewfiles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_files",
        sa.Column(
            "review_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "file_url",
            sa.VARCHAR(length=300),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("fk_review_files_review_id_reviews"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviewfiles")),
    )
    op.drop_table("review_files")
    # ### end Alembic commands ###
