"""remove_status_id_from_baskets

Revision ID: 0e1457bc5224
Revises: cf8048d25600
Create Date: 2025-10-17 23:23:26.159301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0e1457bc5224"
down_revision: Union[str, Sequence[str], None] = "cf8048d25600"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("baskets", "status_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "baskets",
        sa.Column(
            "status_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        op.f("fk_baskets_status_id_basket_statuses"),
        "baskets",
        "basket_statuses",
        ["status_id"],
        ["id"],
    )
    op.create_table(
        "basket_statuses",
        sa.Column(
            "name", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_basket_statuses")),
        sa.UniqueConstraint(
            "name",
            name=op.f("uq_basket_statuses_name"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
